### ISSUE TITLE
Still accepts noncanonic base64

### ISSUE THREAD

**Issue by AljoschaMeyer** [ssbc/ssb-ref#25]
The hash `&sha252shasa2sha2sha252shasa2sha25sha252shas=.sha256` is valid, whereas `&sha252shasa2sha2sha252shasa2sha25sha252shar=.sha256` is invalid (the last character of the base64 encoding is non-canonic). `ref.isLink` accepts both though.

Version 2.13.3

**Comment by dominictarr** [comment]
fixed in 2.13.4
