### ISSUE TITLE
parseMultiServerAddress is deprecated... but ssb-ref uses it?

### ISSUE THREAD

**Issue by stripedpajamas** [ssbc/ssb-ref#28]
I got the `deprecated api used: ssb-ref.parseMultiServerAddress` message recently and looked at the stack, only to find that the offending package was ssb-ref 😢 

in ssb-ref:
`type()` calls `isInvite()` calls `isMultiServerInvite()` calls `parseMultiServerAddress()`

should this function be marked as deprecated if the package itself is using it? if the goal is to warn others from calling parseMultiServerAddress, one idea is to keep the deprecation warning on parseMultiServerAddress, but have parseMultiServerAddress call _parseMultiServerAddress (move the logic there), and _parseMultiServerAddress can be called internally without warning.

**Comment by christianbundy** [comment]
> one idea is to keep the deprecation warning on parseMultiServerAddress, but have parseMultiServerAddress call _parseMultiServerAddress (move the logic there), and _parseMultiServerAddress can be called internally without warning.

I think that's a great idea, I'd merge that PR. :tada:

**Comment by stripedpajamas** [comment]
Opened #29

**Comment by christianbundy** [comment]
Resolved by #29!
