### ISSUE TITLE
The type function is super slow

### ISSUE THREAD

**Issue by arj03** [ssbc/ssb-ref#36]
I was testing something related to backlinks and found it to be extremely slow. Like 90 seconds for 100k messages on my laptop. Quite a bit back and forth and it seems to be `ref.type` that is slow because it checks for [these](https://github.com/ssbc/ssb-ref/blob/68009b9e1f5871b5755476b066c770528a215c2b/index.js#L307) invite and address. Without those 2 checks, we go down to 7 seconds.

The reason why I'm opening an issue is because I want to know if they should be part of backlinks or not.

**Comment by arj03** [comment]
@staltz might be interesting for you related to manyverse.

**Comment by staltz** [comment]
Wow! Great find! It makes a lot of sense to me that ssb-backlinks doesn't need to index (pub) addresses and invites, and can focus instead on `@`, `&`, `%` only.

**Comment by arj03** [comment]
It doesn't seem like either ssb-server, ssb-db (makes sense as backlinks is plugin). Also ssb-invite and ssb-peer-invites doesn't use backlinks.
